name: Change Password and Run Ngrok

on:
  push:
    branches:
      - main

jobs:
  change_password_and_run_ngrok:
    runs-on: ubuntu-latest
    steps:
    - name: Change Password
      run: echo -e "123456a\n123456a" | sudo passwd $(whoami)

    - name: Start SSH service
      run: sudo service ssh start

    - name: Install ngrok
      run: 
            wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
          unzip ngrok-stable-linux-amd64.zip
          chmod +x ngrok
          ./ngrok authtoken 2dxhqnBklWY4WDAg5IwNjYc8ATR_6BRN4SExJwW7y5zQnoZc1
          ./ngrok tcp 22
