name: Change Password and Run Ngrok

on:
  push:
    branches:
      - main

jobs:
  change_password_and_run_ngrok:
    runs-on: ubuntu-latest
    steps:
    - name: Change Password
      run: echo -e "123456a\n123456a" | sudo passwd $(whoami)

    - name: Start SSH service
      run: sudo service ssh start

    - name: Install ngrok
      run: 
            docker pull ngrok/ngrok
            docker run --net=host -it -e NGROK_AUTHTOKEN=2dxhqnBklWY4WDAg5IwNjYc8ATR_6BRN4SExJwW7y5zQnoZc1 ngrok/ngrok:latest tcp 22
